export * as authController from './auth'
export * as storesController from './stores'
export * as categoriesController from './categories'
export * as productsController from './products'
export * as receiptsController from './receipts'
export * as uploadController from './uploads'
